config/routes.rb
Rails.application.routes.draw do

get 'transactions/new'
get 'carts/endd'
get 'carts/show'
get 'carts/some'
get 'some/noti'
get 'ano/create'

devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

resources :products, only: [:show, :index]
resources :some, only: [:noti]
resources :transactions, only: [:new, :create,]
resources :ano, only: [:create]

resource :cart, only: [:show, :endd] do
put 'add/:product_id', to: 'carts#add', as: :add_to
put 'remove/:product_id', to: 'carts#remove', as: :remove_from
end

root 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base

has_many :purchases
has_many :buyers, through: :purchases

# Getting Images
def image
"http://www.arest.pl/ph/#{image_url}/1_addmedium.jpg"
end

def product_id
end  

def cart_action(current_user_id)
if $redis.sismember "cart#{current_user_id}", id
      "Remove from"
else
      "Add to"
end
end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

belongs_to :product
belongs_to :buyer, class_name: 'User'

end

app/models/user.rb
class User < ActiveRecord::Base
  
has_many :purchases, foreign_key: :buyer_id
has_many :products, through: :purchases

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  FIELDS = [:first_name, :last_name, :phone, :website, :company, :fax, :addresses, :credit_cards, :custom_fields]
  attr_accessor *FIELDS

  def has_payment_info?
    braintree_customer_id
  end

  def with_braintree_data!
    return self unless has_payment_info?
    braintree_data = Braintree::Customer.find(braintree_customer_id)

    FIELDS.each do |field|
      send(:"#{field}=", braintree_data.send(field))
    end
    self
  end

  def default_credit_card
    return unless has_payment_info?
    credit_cards.find { |cc| cc.default? }
  end

#

  def cart_count
    $redis.scard "cart#{id}"
  end

  def cart_total_price
    total_price = 0
    get_cart_products.each { |product| total_price+= product.price }
    total_price
  end

  def get_cart_products
    cart_ids = $redis.smembers "cart#{id}"
    Product.find(cart_ids)
  end		

#		
  def purchase_cart_products!
    get_cart_products.each { |product| purchase(product) }
    $redis.del "cart#{id}"
  end
		
  def purchase?(product)
    products.include?(product)
  end

  def purchase(product)
    products << product unless purchase?(product)
  end

end

app/controllers/ano_controller.rb
class AnoController < ApplicationController

	def create
      current_user.purchase_cart_movies!
      redirect_to root_url, notice: "Congraulations! You've purchased new movies successfully!"
  end

  def endd
    cart_ids = $redis.smembers current_user_cart
    @cart_products = Product.find(cart_ids)
   end

  

		 
   def current_user_cart
    "cart#{current_user.id}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
		 		
  def show
    cart_ids = $redis.smembers current_user_cart
    @cart_products = Product.find(cart_ids)
  end

		def endd
    cart_ids = $redis.smembers current_user_cart
    @cart_products = Product.find(cart_ids)
  end      

  def add
    $redis.sadd current_user_cart, params[:product_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:product_id]
    render json: current_user.cart_count, status: 200
  end

		private
  def check_cart!
    if current_user.get_cart_products.blank?
      redirect_to root_url, alert: "Please add some items to your cart before processing your transaction!"
    end
end

  private
  def current_user_cart
    "cart#{current_user.id}"
  end

end 

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @cart_action = @product.cart_action current_user.try :id
  end

  
  end 

app/controllers/some_controller.rb
class SomeController < ApplicationController
  
   
		def noti
			redirect_to new_user_session_path, notice: "Please Log In or Register to contiune shoping!"
  end
		
  end 

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_cart!
  
  def show
  end

  def new
    gon.client_token = generate_new_client_token
  end

  def edit
   @credit_card = current_user.default_credit_card
   @tr_data = edit_customer_tr_data
  end

  def create
    @result = Braintree::Transaction.sale(
              amount: current_user.cart_total_price,
              payment_method_nonce: params[:payment_method_nonce])
    if @result.success?
      current_user.purchase_cart_products!
      redirect_to root_url, notice: "Congraulations! You've purchased new products successfully!"
    else
      flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
      gon.client_token = generate_new_client_token
      render :new
    end
  end

  private
  def generate_new_client_token
    Braintree::ClientToken.generate
  end

def check_cart!
    if current_user.get_cart_products.blank?
      redirect_to root_url, alert: "Please add some items to your cart before processing your transaction!"
    end  
end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/carts/endd.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">

<div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
   
<h4> You are about to buy following <span class="cart-count"><%=current_user.cart_count%></span> products at total price of <span class="cart-count"><%=current_user.cart_total_price%></span> Euro. </h4>
  
   </div>

   <% @cart_products.each do |product|%>

   <div data-equalizer class="cart-movie large-12 column mb1">
   <div class="column large-2 text-center p0" data-equalizer-watch>
   <%=link_to product do%>
   <%=image_tag product.image, class: "radius-l1"%>

   <%end%>

   </div>

   <div class="column large-7 glassy-bg text-center" data-equalizer-watch>

    <p class="scale ptm"> <%= product.name %> </p>
    </div>

    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>

    <%=link_to "" , data: {targetUrl: remove_from_cart_path(product)} do%>


    

   <%end%>
    <h4 class="scale">$ <%= product.price %></h4>
    </div>

</div>

<%end%>

<div id="mybutton">

<%=link_to "Pay #{current_user.cart_total_price}€", transactions_new_path, class: "button" unless current_user.get_cart_products.blank?%>
</div>




</div>

app/views/carts/show.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">

   <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
   <h4>My Cart</h4>
   <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> products.</p>
			<p class="mb0"> Total price of all items in your Cart is <span class="cart-count"><%=current_user.cart_total_price%></span> Euro. </p>
  
   </div>

   <% @cart_products.each do |product|%>


   <div data-equalizer class="cart-movie large-12 column mb1">

   <div class="column large-2 text-center p0" data-equalizer-watch>

   <%=link_to product do%>

   <%=image_tag product.image, class: "radius-l1"%>

   <%end%>

   </div>

   <div class="column large-7 glassy-bg text-center" data-equalizer-watch>

    <p class="scale ptm"> <%= product.name %> </p>
    </div>

    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
    <%=link_to "" , data: {targetUrl: remove_from_cart_path(product)} do%>

    <i class="fi-x right"></i>
   <%end%>
    <h3 class="scale">€<%= product.price %></h3>
    </div>

</div>

<%end%>


<div id="mybutton">            
<%=link_to "To Checkout", carts_endd_path, class: "button" unless current_user.get_cart_products.blank?%>
</div>


</div>

app/views/carts/some.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">

   <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
   
			<p><span class="cart-count"><%=current_user.del_cart%></span></p>
  
   </div>

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
	<div class="row">
		<%is_alert = alert.present? ? "alert" : ""%>
		<div data-alert class="alert-box <%=is_alert%>">
			<%=notice || alert%>
			<a href="#" class="close">&times;</a>
		</div>
	</div>
<%end%>

app/views/layouts/_header.html.erb
<div class="row">
  <nav class="top-bar column" data-topbar>

    <ul class="title-area">
      <li class="name">
        <h1>
          <a href="/">
            <i class="fi-laptop"></i> Avan Computers
          </a>
        </h1>
      </li>
      <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">

      <!-- Right Nav Section -->
      <ul class="right">
        <%if signed_in?%>
          <li>
            <%= link_to cart_path do%>
              <i class="fi-shopping-cart"></i> My Cart (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
          </li>
          <li><%=link_to current_user.email, edit_user_registration_path%></li>
          <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
        <%else%>
          <li><%=link_to "Register", new_user_registration_path%></li>
          <li><%=link_to "Login", new_user_session_path%></li>
        <%end%>

      

</ul>






      <!-- Left Nav Section -->
      <ul class="left">








        <li class="has-form">
          <div class="row collapse">
            <div class="large-8 small-9 columns">
              <input type="text" class="radius-ls expand" placeholder="Find Product">
            </div>

            <div class="large-4 small-3 columns">
              <a href="#" class=" radius-rs button">Search</a>


            </div>




          </div>
        </li>
      </ul>

    </section>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Avan Computers" %></title>
    <link rel="shortcut icon" href="<%=asset_path("logo1.png")%>" >

				<%= include_gon %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/header"%>

    <%= render "layouts/alerts" %>

    <div id="main-content" class="row full-min-height">
      <%= yield %>
    </div>

    <footer class="row">
      <div class="large-12 columns">
        <hr>
        <p>© Avan Computers 2015</p>
      </div>
    </footer>

    <%= javascript_include_tag "application" %>
    
  </body>
</html>

app/views/products/index.html.erb
<h4 class="column">Featured Products - Best Price Guarantee !!</h4>

<div class="column">

  <ul class="movies-grid no-bullet row">

    <% @products.each do |product| %>

      <li class="large-3 medium-4 small-12 column">

        <div class="movie-card padly">

          <%= link_to product, class: "poster" do %>

            <%= image_tag product.image %>

          <% end %>

          <div class="movie-info ell glassy-bg padmy padlx">

            <div class="title">

              <h6><%= product.name %> <span><%= product.date_added %></span></h6>
            </div>

            <p class="left price label movie-label radius">$ 

<%= product.price %></p>

            <%= link_to product.product_id, class: "right" do %>

              <%= image_tag asset_path("imdb_logo.png") %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/products/show.html.erb
<div class="large-3 small-12 column">

<%=image_tag @product.image%>

</div>
<div class="large-9 small-12 column">

  <h3>
    <%= @product.name %>
    <%= @product.date_added %>
    <%=link_to @product.product_id do%>

      <%=image_tag asset_path("imdb_logo.png")%>

    <%end%>
  </h3>
  <p class="label movie-label radius mb1">€ <%= @product.price %></p>

  <p><%= @product.description %></p>

</h3> 


<%if not signed_in?%>
<div class="button">
 <i class="fi-shopping-cart"></i>
<%= link_to "Add To Cart", some_noti_path %>

<%end%>


<%if signed_in?%>
<%=link_to "", class: "button", data: {target: @cart_action, addUrl: add_to_cart_path(@product), removeUrl: remove_from_cart_path(@product)} do%>
      
<i class="fi-shopping-cart"></i>
<span><%=@cart_action%></span> Cart

<%end%>

<%if signed_in?%>
<%=link_to "Continue Shopping", root_path, class: "button" %>
<%end%>
<%end%>

  
<%if signed_in?%>
<%= link_to cart_path do %>
<div class="button">

              <i class="fi-shopping-cart"></i> My Cart (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
<%end%>

</div>

app/views/transactions/endd.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">

<div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
   
<h4> You are about to buy following <span class="cart-count"><%=current_user.cart_count%></span> products at total price of <span class="cart-count"><%=current_user.cart_total_price%></span> Euro. </h4>
  
   </div>

   <% @cart_products.each do |product|%>

   <div data-equalizer class="cart-movie large-12 column mb1">
   <div class="column large-2 text-center p0" data-equalizer-watch>
   <%=link_to product do%>
   <%=image_tag product.image, class: "radius-l1"%>

   <%end%>

   </div>

   <div class="column large-7 glassy-bg text-center" data-equalizer-watch>

    <p class="scale ptm"> <%= product.name %> </p>
    </div>

    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>

    <%=link_to "" , data: {targetUrl: remove_from_cart_path(product)} do%>


    

   <%end%>
    <h4 class="scale">$ <%= product.price %></h4>
    </div>

</div>

<%end%>

<div id="mybutton">

<%=link_to "Pay #{current_user.cart_total_price}€", new_transaction_path, class: "button" unless current_user.get_cart_products.blank?%>
</div>




</div>

app/views/transactions/new.html.erb
<%= include_gon %>
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
  <h2 class="mbs">New Transaction</h2>
  <p>Please enter your payment details:</p>
  <%= form_tag transactions_path do%>
    <div id="dropin"></div>
    <%=submit_tag "Pay #{current_user.cart_total_price}$", class: "button mt1" %>
  <%end%>
</div>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>